### ISSUE TITLE
NEW ISSUES REQUEST

### ISSUE THREAD

**Issue by clintonjosephs** [olawalecoder/Portfolio#4]
Hello Bami 😊
We looked at the project and found a few issues
- It would be nice if the `title` tag bears your name instead of DOCUMENT 👍 
- Please add the other font-awesome icons to depict ANGELIST AND MEDIUM 🥲 
- I noticed the issue you have with scrolling to the right on mobile view, I suggest you just set the width of your containers to 100% to eliminate scroll 😃 
- It would be nice if the social media icon is placed on the footer section as well 👍 

💯 Good job on the entire design and your work with gradient and CSS placement!!

**Comment by olawalecoder** [comment]
Thank you for the review. :+1: 
I have made all changes advised. :smiley:
