### ISSUE TITLE
# Issue about PR message 

### ISSUE THREAD

**Issue by selma-belhadj** [olawalecoder/Portfolio#9]
## PR message 
Hello @olawalecoder.
You have done a great job till now. there are just some changes you could modify:
- Please just modify the message of the PR so it can be more descriptive, you can use that if you want:  
 In this PR, I have done the following tasks :
     - Created Mobile menu
     - Used Js to activate the mobile menu

**Comment by mrparkersson** [comment]
Good job @olawalecoder. Your project looks impressive! 
But I will second @selma-belhadj
